quarkus.application.name=balance-service
quarkus.http.port=8081

# Configuração do Kafka Consumer
# Kafka Consumer Configuration
kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.transaction-in.connector=smallrye-kafka
mp.messaging.incoming.transaction-in.topic=transactions
mp.messaging.incoming.transaction-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.transaction-in.group.id=balance-service-group